// <auto-generated />
using System;
using System.Collections.Generic;
using ControleDeFrete.API.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeFrete.API.Migrations
{
    [DbContext(typeof(ControleDeFreteContext))]
    partial class ControleDeFreteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("Documento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataEntrega")
                        .HasColumnType("date");

                    b.Property<bool>("Entregue")
                        .HasColumnType("bit");

                    b.Property<int>("FreteId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Destino", "ControleDeFrete.API.Domain.Entites.Entrega.Destino#Localizacao", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Destino_Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Destino_Estado");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Destino_Latitude");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Destino_Logradouro");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Destino_Longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("FreteId");

                    b.ToTable("Entregas", (string)null);
                });

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Frete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("DataCarregamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("DataEmissao");

                    b.Property<DateOnly?>("DataEntrega")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDescarrego")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMotorista")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Origem", "ControleDeFrete.API.Domain.Entites.Frete.Origem#Localizacao", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Origem_Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Origem_Estado");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Origem_Latitude");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Origem_Logradouro");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Origem_Longitude");
                        });

                    b.HasKey("Id");

                    b.ToTable("Fretes", (string)null);
                });

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("DataCadastro")
                        .HasColumnType("date");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("Documento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Endereco", "ControleDeFrete.API.Domain.Entites.Motorista.Endereco#Localizacao", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Origem_Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Origem_Estado");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Origem_Latitude");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Origem_Logradouro");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Origem_Longitude");
                        });

                    b.HasKey("Id");

                    b.ToTable("Motoristas", (string)null);
                });

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Placa", "ControleDeFrete.API.Domain.Entites.Veiculo.Placa#Placa", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("nchar(7)")
                                .HasColumnName("Placa")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.ToTable("Veiculos", (string)null);
                });

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Cliente", b =>
                {
                    b.OwnsOne("ControleDeFrete.API.Domain.ValueObjects.Localizacao", "Endereco", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("int");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Estado");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Logradouro");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Entrega", b =>
                {
                    b.HasOne("ControleDeFrete.API.Domain.Entites.Frete", null)
                        .WithMany("Entregas")
                        .HasForeignKey("FreteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleDeFrete.API.Domain.Entites.Frete", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
